### ISSUE TITLE
Can you help me pack an x64 Windows dll and lib for testing input box form filling？

### ISSUE THREAD

**Issue by Caesar454905970** [jwezorek/vs_pdfium#9]

**Comment by jwezorek** [comment]
The solution is set up to build to a static library. If you want to build to a DLL you need to change settings in Visual Studio. There are two toplevel projects in the solution, pdfium_lib and render_pdf. In Solution Explorer, right click on pdfium_lib and select "properties" then "Configuration Properties > General" change "Configuration Type" to "Dynamic Library (.DLL)" in the debug and release x64 configurations.

**Comment by Caesar454905970** [comment]
I used your method to compile and got an error
![e81a88da20585aa049eb6774c4b432c](https://github.com/user-attachments/assets/cc769961-f402-4942-aeb9-6cfb130e6a54)

**Comment by Caesar454905970** [comment]
![e81a88da20585aa049eb6774c4b432c](https://github.com/user-attachments/assets/c9944032-b8b9-465a-bc2e-6db9cf7f7546)

**Comment by jwezorek** [comment]
That's a linker error that is saying Visual Studio can't find "turbojpeg-static.lib" in vs_pdfium/pdfium_lib/pdfium/bin/x64/turbojpeg-static.lib. Verify that this file is actually there first of all.

That binary is checked into this repository and the solution is set up to link to it by having the relative path ".\pdfium\bin\x64" set in  <pdfium_lib properties> > Librarian > General > Additional Library Directories.

If the file is there and Visual Studio is not finding it, I am not sure what could be causing this unless perhaps you changed the working directory?

**Comment by Caesar454905970** [comment]
build dll，show other error!
![image](https://github.com/user-attachments/assets/2d9bd30b-3b99-445f-88d2-2823781108ee)

**Comment by jwezorek** [comment]
Well that looks like because you changed pdfium_lib to be a DLL. The render_pdf project is set up to link to a static library. It's not going to magically just work. 
If you want "implicitely link" to the DLL you can do so with minor changes I think. You need to find where the stub .lib file for pdfium_lib is being created and change render_pdf's "additional library directories" such that it finds it. Doing that should get render_pdf building again but then to actually run it the DLL will need to be in the same directory as the executable. You either copy it there or set up the PATH environment variable to that the exe loader finds it.
